### ISSUE TITLE
transformation between conll and standoff

### ISSUE THREAD

**Issue by shaoxiongji** [jeniyat/WNUT_2020_NER#2]
Predictions are converted to conll after prediction made. From line [224](https://github.com/jeniyat/WNUT_2020/blob/4aa91f86e618f5b4195b7183b61defb51acb8666/code/baseline_CRF/crf_ner_wlp.py#L224) to [231](https://github.com/jeniyat/WNUT_2020/blob/4aa91f86e618f5b4195b7183b61defb51acb8666/code/baseline_CRF/crf_ner_wlp.py#L231) in [code/baseline_CRF/crf_ner_wlp.py](https://github.com/jeniyat/WNUT_2020/blob/master/code/baseline_CRF/crf_ner_wlp.py), the format is converted into standoff, and again converted into conll. Could you plz explain why we need this double conversion?

**Comment by jeniyat** [comment]
This code was added as a part of sanity check for the conversation script. You can easily comment it out.
