### ISSUE TITLE
Discrepency between the standoff and the conll data.

### ISSUE THREAD

**Issue by blester125** [jeniyat/WNUT_2020_NER#3]
Hi! I was looking at the dataset and I found some differences in some of the counts when looking at the standoff vs the conll data. When you look at the number of sentence in the standoff training data it matches the number in your readme.

```
$ cat data/train_data/Standoff_Format/*.txt | wc -l
8436
$ cat data/dev_data/Standoff_Format/*.txt | wc -l
2838
$ cat data/test_data/Standoff_Format/*.txt | wc -l
2809
```

(Note that number of sentences in the standoff format test data don't seem to match your read me either unless the sentences in the read me aren't equivalent to steps in the protocol?) 

However when I looked at the conll formatted data, first using my custom conll reading code and then using the `conllu` package from pypi, I am seeing more sentences in the training and development data (8444 and 2839 respectively) and fewer sentences in the test data (2803)

Here is the code I used to get the counts.

```python
from conllu import parse
from glob import iglob
docs = 0
sentences = 0
for file in glob("data/train_data/Conll_Format/*_conll.txt"):
    docs += 1
    with open(file) as f:
        sents = parse(f.read(), fields=["suface", "NER"])
        sentences += len(sents)
print(f"# of documents: {docs}")
print(f"# of sentences: {sentences}")
```
```
# of documents: 370
# of sentences: 8444
```

Any idea what is going on?

**Comment by jeniyat** [comment]
Can you try to use [read_file](https://github.com/jeniyat/WNUT_2020/blob/55822d5d30843501b6293a0202479bbe4166bee8/code/baseline_CRF/crf_ner_wlp.py#L50) function and test the line counts? FYI, we used the [official bart script] (https://github.com/nlplab/brat/blob/master/tools/anntoconll.py) to convert the standoff to conll format. Please let us know, if you think any of the scripts return inconsistent results.
