### ISSUE TITLE
Is relation extraction still a part of this Shared Task?

### ISSUE THREAD

**Issue by stgrue** [jeniyat/WNUT_2020_NER#4]
Hi! I was looking at the released data and code and noticed some things that led me to wonder: Is relation extraction still part of this Shared Task?

1. There are inconsistencies between the Standoff and the CoNLL data, making combining the data difficult. (A similar issue was already raised in https://github.com/jeniyat/WNUT_2020/issues/3.) These are related to tokenization. Two randomly chosen examples:
    - In [`protocol_7.ann`](https://github.com/jeniyat/WNUT_2020/blob/55822d5d30843501b6293a0202479bbe4166bee8/data/dev_data/Standoff_Format/protocol_7.ann), line 268, the token `untransformed ` actually contains a space at the end, which messes up token boundaries. This seems to be because it is a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) and happens multiple times in the data.
    - [`protocol_102_conll.txt`](https://github.com/jeniyat/WNUT_2020/blob/55822d5d30843501b6293a0202479bbe4166bee8/data/dev_data/Conll_Format/protocol_102_conll.txt), line 149, contains the token `FLowCamMake`, labeled as `B-Device`. In contrast, [`protocol_102.ann`](https://github.com/jeniyat/WNUT_2020/blob/55822d5d30843501b6293a0202479bbe4166bee8/data/dev_data/Standoff_Format/protocol_102.ann) correctly identifies that there is actually an entity boundary with in this sequence of characters, splitting it up into `FLowCam` and `Make sure`.

2. Unless I am missing something, there does not seem to be an official evaluation script for relations/events. The Standoff-to-CoNLL conversion script also seems to completely ignore relations. The baseline system also seems to only predict entities.

3. The [Readme.md](https://github.com/jeniyat/WNUT_2020/blob/master/Readme.md) is titled "WNUT 2020: Named Entity Extraction", not mentioning relations.

So my question is: Are relations still part of the Shared Task? If so, will an official evaluation script be released for them?

**Comment by noisy-text** [comment]
Sorry for the confusion. Jeniya (co-organizer) is working on the evaluation script and a baseline model for relation extraction. We hope to be able to release it in a week.  

We plan to use only the Standoff format (not CoNLL) for relation extraction task, and hold a separate evaluation period for relation task (about a week after the named entity task evaluation). We are currently thinking to provide the gold name entities to the participants to use in the relation extraction evaluation.

**Comment by kaushikacharya** [comment]
> 1. There are inconsistencies between the Standoff and the CoNLL data, making combining the data difficult. (A similar issue was already raised in #3.)

I have also observed similar discrepancy in several files.

e.g. protocol_101 (2nd line)
![image](https://user-images.githubusercontent.com/4562867/90259463-afc2d300-de67-11ea-93b6-7e0d4d5a1656.png)

As per Conll_Format/protocol_101_conll.txt, "to" is Action and not "Go"
```
Go	O
to	B-Action
the	O
```
Whereas as per Standoff_Format/protocol_101.ann
`T3	Action 135 137	Go`

Standoff_Format seems to be the correct one.

**Comment by jeniyat** [comment]
Thanks for pointing out these issues. I will take a look into the conversion script and update the scipt and Conll files. Basically the Conll files are created from the standoff format. Please use the standoff format files  if you prefer.

**Comment by jeniyat** [comment]
@kaushikacharya & @stgrue  Please check out the updated `anntoconll_wlp.py` script and the updated Conll data.  We have corrected the empty space issues in the Conll data.

**Comment by jeniyat** [comment]
@stgrue, please check this repository for the RE evaluation script: https://github.com/jeniyat/WNUT_2020_RE

**Comment by kaushikacharya** [comment]
@jeniyat 
Your updated script has corrected previously mentioned error instances. But has introduced error in new places.

![image](https://user-images.githubusercontent.com/4562867/90327965-308fe500-dfb6-11ea-8249-75d9a8764626.png)

train_data/Conll_Format/protocol_101_conll.txt
```
with your user	B-Reagent
name	I-Reagent
```

train_data/Standoff_Format/protocol_101.ann
`T30	Reagent 89 98	user name`

Two issues:

- https://stackoverflow.com/questions/27416164/what-is-conll-data-format
     As per David McClosky's answer (username: dmcc), 
    > Each line represents a **single word** with a series of tab-separated fields.

- As Reagent entity is 

> user name

conll file should have 
```
user	B-Reagent
name	I-Reagent
```	

Anyway, as suggested by you, better to use standoff format.

**Comment by jeniyat** [comment]
@kaushikacharya, please check the updated conll conversion script and data, if you still wanna check the conll format.

**Comment by jeniyat** [comment]
@kaushikacharya please check the updated conll conversion script and data, if you want to utilize check the conll format.
